package scg.roadbeat.modelo;
// Generated 10 abr 2024 13:36:01 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * CodigosSalas generated by hbm2java
 */
@Entity
@Table(name = "codigos_salas", catalog = "roadbeat", uniqueConstraints = @UniqueConstraint(columnNames = "idSala"))
public class CodigosSalas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cod;
	private Salas sala;
	private Boolean cerrada;

	public CodigosSalas() {
	}

	public CodigosSalas(String codSala) {
		this.cod = codSala;
	}

	public CodigosSalas(String codSala, Salas salas, Boolean cerrada) {
		this.cod = codSala;
		this.sala = salas;
		this.cerrada = cerrada;
	}

	@Id

	@Column(name = "cod", unique = true, nullable = false, length = 10)
	public String getCodSala() {
		return this.cod;
	}

	public void setCodSala(String codSala) {
		this.cod = codSala;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sala", unique = true)
	public Salas getSalas() {
		return this.sala;
	}

	public void setSalas(Salas salas) {
		this.sala = salas;
	}

	@Column(name = "cerrada")
	public Boolean getCerrada() {
		return this.cerrada;
	}

	public void setCerrada(Boolean cerrada) {
		this.cerrada = cerrada;
	}

}
