package scg.roadbeat.modelo;

// Generated 10 abr 2024 13:36:01 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Historial generated by hbm2java
 */
@Entity
@Table(name = "historial", catalog = "roadbeat")
public class Historial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Salas sala;
	private Usuarios usuario;

	public Historial() {
	}

	public Historial(Salas salas, Usuarios usuarios) {
		this.sala = salas;
		this.usuario = usuarios;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sala")
	public Salas getSalas() {
		return this.sala;
	}

	public void setSalas(Salas salas) {
		this.sala = salas;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usuario")
	public Usuarios getUsuarios() {
		return this.usuario;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuario = usuarios;
	}

}
