package scg.roadbeat.modelo;
// Generated 10 abr 2024 13:36:01 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Salas generated by hbm2java
 */
@Entity
@Table(name = "salas", catalog = "roadbeat")
public class Salas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nombre;
	private Date fecha;
	private String playlist;
	private Usuarios anfitrion;
	

	public Salas() {
	}

	public Salas(Date fecha) {
		this.fecha = fecha;
	}

	public Salas(String nombre, Usuarios usuarios) {
		this.nombre = nombre;
		this.anfitrion = usuarios;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "anfitrion")
	public Usuarios getUsuarios() {
		return this.anfitrion;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.anfitrion = usuarios;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "playlist", length = 100)
	public String getLinkPlaylist() {
		if( this.playlist != null) {
			return this.playlist;
		} else {
			return  " ";
		}
		
	}
	
	public void setLinkPlaylist(String playlist) {
		this.playlist = playlist;
	}
	
	@Column(name = "nombre", length = 100)
	public String getNombre() {
		if( this.nombre != null) {
			return this.nombre;
		} else {
			return  " ";
		}
		
	}
	
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
