package scg.roadbeat.modelo;
// Generated 10 abr 2024 13:36:01 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "roadbeat")
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String email;
	private String nombre;
	private String username;
	private String password;
	private Integer canciones;
	private String foto;
	private Boolean closed;

	public Usuarios() {
	}

	public Usuarios(String email, String nombre, String username, String password, Boolean closed) {
		this.email = email;
		this.nombre = nombre;
		this.username = username;
		this.password = password;
		this.closed = closed;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "username", nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@Column(name = "canciones", nullable = false, length = 30)
	public Integer getCanciones() {
		return this.canciones;
	}
	
	public void setCanciones(Integer canciones) {
		this.canciones = canciones;
	}
	
	@Column(name = "foto", length = 900)
	public String getFoto() {
		return this.foto;
	}
	
	public void setFoto(String foto) {
		this.foto = foto;
	}
	
	@Column(name = "closed")
	public Boolean getClosed() {
		return this.closed;
	}
	
	public void setClosed(Boolean closed) {
		this.closed = closed;
	}

}
